#!/usr/bin/python3
# File:         fitsdel
# Version:      20221128
# Author:       KOBS/Sifan Kahale
# deletes fits files in allskysqm 
# Lists fits files in allskysqm web dir

FITSLOC = "/var/www/html/allsky/images/"
import os
numfile = 0

for root, dirs, files in os.walk(FITSLOC):
 for file in files:
  if file.endswith(".fit"):
   numfile += 1
   fitsfile = os.path.join(root,file)
   print(fitsfile)

print("Number of fits files found:  %d" % numfile)

